const fs = require('fs');
const path = require('path');

const PHOTOS_DIR = path.join(__dirname, 'images', 'photos');
const OUTPUT_FILE = path.join(__dirname, 'photos_data.js');

try {
    if (!fs.existsSync(PHOTOS_DIR)) {
        console.log(`Creating directory: ${PHOTOS_DIR}`);
        fs.mkdirSync(PHOTOS_DIR, { recursive: true });
    }

    console.log(`Scanning directory: ${PHOTOS_DIR}...`);
    const files = fs.readdirSync(PHOTOS_DIR);
    
    // Filter for common image extensions
    const imageExtensions = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];
    const imageFiles = files
        .filter(file => imageExtensions.includes(path.extname(file).toLowerCase()))
        .map(file => `images/photos/${file}`);

    console.log(`Found ${imageFiles.length} images.`);

    // Write array to photos_data.js
    const content = `// This file is auto-generated by generate_gallery_data.js
// Do not edit this file manually.
const LOCAL_PHOTOS = ${JSON.stringify(imageFiles, null, 2)};
`;

    fs.writeFileSync(OUTPUT_FILE, content, 'utf8');
    console.log(`Successfully generated ${OUTPUT_FILE}`);
} catch (err) {
    console.error('Error scanning images/photos:', err);
}
