const fs = require('fs');
const path = require('path');

const ALBUM_ROOT = path.join(__dirname, 'images', 'album');
const PHOTOS_DIR = path.join(__dirname, 'images', 'photos');
const OUTPUT_FILE = path.join(__dirname, 'photos_data.js');

const allowedExtensions = ['.jpg', '.jpeg', '.png', '.webp', '.mp4', '.webm', '.mov'];
let allMediaFiles = [];

// Helper to recursively scan folders
function scanDirectory(dir, relativeRoot) {
    if (!fs.existsSync(dir)) return;
    const items = fs.readdirSync(dir);
    for (const item of items) {
        const fullPath = path.join(dir, item);
        const relativePath = path.join(relativeRoot, item).replace(/\\/g, '/');
        const stat = fs.statSync(fullPath);
        
        if (stat.isDirectory()) {
            scanDirectory(fullPath, relativePath);
        } else {
            const ext = path.extname(item).toLowerCase();
            if (allowedExtensions.includes(ext)) {
                const isVid = ['.mp4', '.webm', '.mov'].includes(ext);
                let thumbPath = relativePath;
                
                if (isVid) {
                    thumbPath = 'images/assets/images/engagement_ring.webp';
                } else if (dir.startsWith(ALBUM_ROOT)) {
                    // Match the deterministic thumbnail filename from PowerShell
                    const relativeAlbumPath = path.relative(ALBUM_ROOT, fullPath);
                    const normalizedPath = relativeAlbumPath.replace(/\\/g, '_').replace(/\//g, '_').replace(/ /g, '_');
                    const thumbFileName = normalizedPath.substring(0, normalizedPath.length - ext.length) + '.jpg';
                    const localThumbFile = path.join(__dirname, 'images', 'thumbnails', thumbFileName);
                    
                    if (fs.existsSync(localThumbFile)) {
                        thumbPath = `images/thumbnails/${thumbFileName}`;
                    }
                }
                
                allMediaFiles.push({
                    src: relativePath,
                    thumb: thumbPath,
                    type: isVid ? 'video' : 'image'
                });
            }
        }
    }
}

try {
    // Scan images/album
    if (fs.existsSync(ALBUM_ROOT)) {
        console.log(`Scanning album root: ${ALBUM_ROOT}`);
        scanDirectory(ALBUM_ROOT, 'images/album');
    }
    
    // Scan images/photos
    if (fs.existsSync(PHOTOS_DIR)) {
        console.log(`Scanning photos dir: ${PHOTOS_DIR}`);
        scanDirectory(PHOTOS_DIR, 'images/photos');
    }

    console.log(`Found ${allMediaFiles.length} media files (images & videos).`);

    // Write array to photos_data.js
    const content = `// This file is auto-generated by generate_gallery_data.js
// Do not edit this file manually.
const STATIC_GALLERY = ${JSON.stringify(allMediaFiles, null, 2)};
`;

    fs.writeFileSync(OUTPUT_FILE, content, 'utf8');
    console.log(`Successfully generated ${OUTPUT_FILE}`);
} catch (err) {
    console.error('Error scanning media directories:', err);
}
